package frc.robot.subsystems.armevator;

public enum ArmevatorPose {
  STARTING,
  CLIMB,
  CORAL_HP_LOAD,
  CORAL_L4_SCORE,
  CORAL_L3_SCORE,
  CORAL_L2_SCORE,
  CORAL_L1_SCORE,
  ALGAE_INTAKE,
  ALGAE_HANDOFF,
  ALGAE_NET_SCORE,
  ALGAE_L3_PLUCK,
  ALGAE_L3_DROP,
  ALGAE_L2_PLUCK,
  ALGAE_L2_DROP,
}
